version: "3.8"

services:
  driving-bot:
    build: .
    container_name: driving-bot
    restart: unless-stopped
    expose:
      - "3000"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-driving-bot
    restart: always
    # We specify the --config flag specifically for the 'run' subcommand
    command: tunnel --config /etc/cloudflared/driving-bot.yml run
    volumes:
      - /Users/rajagrawal/.cloudflared:/etc/cloudflared:ro
    depends_on:
      - driving-bot